export type Config = {
	FPS: number;
	screenWidth: number;
	screenHeight: number;
	maxFPS: number;
	layerWidth: number;
	layerHeight: number;
	debug: boolean;
	fullCanvas: boolean;
	useCursor: boolean;
	interpolation: boolean;
	resolution: number;
	layers: number;
	blobs: number;
	blobsMinSize: number;
	blobsMaxSize: number;
	blobsSpeed: number;
	distance: number;
	strokeMaxSize: number;
	strokeMinSize: number;
};
